# Generated by Django 5.0.6 on 2024-06-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0003_title_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='profileimage',
        ),
    ]
