# Generated by Django 5.0.6 on 2024-07-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0004_user_email_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
