# Generated by Django 5.0.6 on 2024-06-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0004_login_logout_rename_image_user_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileimage',
            new_name='profileimages',
        ),
    ]
