# Generated by Django 5.0.6 on 2024-07-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0005_alter_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
