# Generated by Django 5.0.6 on 2024-06-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0005_rename_profileimage_user_profileimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileimages',
        ),
    ]
