# Generated by Django 5.0.6 on 2024-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0006_user_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
