# Generated by Django 5.0.6 on 2024-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0006_remove_user_profileimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Logout',
        ),
    ]
