# Generated by Django 5.0.6 on 2024-06-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0007_userchangepassword_delete_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
