# Generated by Django 5.0.6 on 2024-06-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0008_alter_title_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChangePassword',
        ),
    ]
