# Generated by Django 5.0.6 on 2024-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0008_perslib_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perslib',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
