# Generated by Django 5.0.6 on 2024-07-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0009_alter_perslib_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
